-- Expand CuisineKey enum (round 2)
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'GEORGIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'AZERBAIJANI';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'ARMENIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'UZBEK';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'CENTRAL_ASIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'SYRIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'EGYPTIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'TUNISIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'BALKAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'PORTUGUESE';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'POLISH';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'SWEDISH';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'MALAYSIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'PERUVIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'ARGENTINIAN';

-- Expand RecipeCategory enum (round 2)
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'GRILL';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'RICE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'NOODLE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'SEAFOOD';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'CASSEROLE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'CURRY';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'DUMPLING';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'PIE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'WRAP';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'CAKE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'COOKIE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'PRESERVE';
