export const CuisineKey = {
  Turkish: 'TURKISH',
  Italian: 'ITALIAN',
  Mexican: 'MEXICAN',
  Chinese: 'CHINESE',
  Japanese: 'JAPANESE',
  Indian: 'INDIAN',
  French: 'FRENCH',
  Greek: 'GREEK',
  American: 'AMERICAN',
  Mediterranean: 'MEDITERRANEAN',
  Thai: 'THAI',
  Spanish: 'SPANISH',
  Korean: 'KOREAN',
  MiddleEastern: 'MIDDLE_EASTERN',
  German: 'GERMAN',
  British: 'BRITISH',
  Vietnamese: 'VIETNAMESE',
  Lebanese: 'LEBANESE',
  Moroccan: 'MOROCCAN',
  Brazilian: 'BRAZILIAN',
  Russian: 'RUSSIAN',
  Persian: 'PERSIAN',
  Caribbean: 'CARIBBEAN',
  Filipino: 'FILIPINO',
  Indonesian: 'INDONESIAN',
  Pakistani: 'PAKISTANI',
  Caucasian: 'CAUCASIAN',
  African: 'AFRICAN',
  Other: 'OTHER',
} as const;

export type CuisineKey = (typeof CuisineKey)[keyof typeof CuisineKey];

export const CUISINE_KEY_VALUES: readonly CuisineKey[] = [
  CuisineKey.Turkish,
  CuisineKey.Italian,
  CuisineKey.Mexican,
  CuisineKey.Chinese,
  CuisineKey.Japanese,
  CuisineKey.Indian,
  CuisineKey.French,
  CuisineKey.Greek,
  CuisineKey.American,
  CuisineKey.Mediterranean,
  CuisineKey.Thai,
  CuisineKey.Spanish,
  CuisineKey.Korean,
  CuisineKey.MiddleEastern,
  CuisineKey.German,
  CuisineKey.British,
  CuisineKey.Vietnamese,
  CuisineKey.Lebanese,
  CuisineKey.Moroccan,
  CuisineKey.Brazilian,
  CuisineKey.Russian,
  CuisineKey.Persian,
  CuisineKey.Caribbean,
  CuisineKey.Filipino,
  CuisineKey.Indonesian,
  CuisineKey.Pakistani,
  CuisineKey.Caucasian,
  CuisineKey.African,
  CuisineKey.Other,
];

const CUISINE_KEY_SET: ReadonlySet<string> = new Set(CUISINE_KEY_VALUES);

export const isCuisineKey = (v: unknown): v is CuisineKey =>
  typeof v === 'string' && CUISINE_KEY_SET.has(v);
