export const RecipeCategory = {
  Breakfast: 'BREAKFAST',
  Brunch: 'BRUNCH',
  Lunch: 'LUNCH',
  Dinner: 'DINNER',
  Dessert: 'DESSERT',
  Snack: 'SNACK',
  Drink: 'DRINK',
  Smoothie: 'SMOOTHIE',
  Soup: 'SOUP',
  Stew: 'STEW',
  Salad: 'SALAD',
  Appetizer: 'APPETIZER',
  SideDish: 'SIDE_DISH',
  MainCourse: 'MAIN_COURSE',
  Pasta: 'PASTA',
  Pizza: 'PIZZA',
  Sandwich: 'SANDWICH',
  Bread: 'BREAD',
  Baking: 'BAKING',
  Sauce: 'SAUCE',
  Grill: 'GRILL',
  Rice: 'RICE',
  Noodle: 'NOODLE',
  Seafood: 'SEAFOOD',
  Casserole: 'CASSEROLE',
  Curry: 'CURRY',
  Dumpling: 'DUMPLING',
  Pie: 'PIE',
  Wrap: 'WRAP',
  Cake: 'CAKE',
  Cookie: 'COOKIE',
  Preserve: 'PRESERVE',
} as const;

export type RecipeCategory = (typeof RecipeCategory)[keyof typeof RecipeCategory];

export const RECIPE_CATEGORY_VALUES: readonly RecipeCategory[] = [
  RecipeCategory.Breakfast,
  RecipeCategory.Brunch,
  RecipeCategory.Lunch,
  RecipeCategory.Dinner,
  RecipeCategory.Dessert,
  RecipeCategory.Snack,
  RecipeCategory.Drink,
  RecipeCategory.Smoothie,
  RecipeCategory.Soup,
  RecipeCategory.Stew,
  RecipeCategory.Salad,
  RecipeCategory.Appetizer,
  RecipeCategory.SideDish,
  RecipeCategory.MainCourse,
  RecipeCategory.Pasta,
  RecipeCategory.Pizza,
  RecipeCategory.Sandwich,
  RecipeCategory.Bread,
  RecipeCategory.Baking,
  RecipeCategory.Sauce,
  RecipeCategory.Grill,
  RecipeCategory.Rice,
  RecipeCategory.Noodle,
  RecipeCategory.Seafood,
  RecipeCategory.Casserole,
  RecipeCategory.Curry,
  RecipeCategory.Dumpling,
  RecipeCategory.Pie,
  RecipeCategory.Wrap,
  RecipeCategory.Cake,
  RecipeCategory.Cookie,
  RecipeCategory.Preserve,
];

const RECIPE_CATEGORY_SET: ReadonlySet<string> = new Set(RECIPE_CATEGORY_VALUES);

export const isRecipeCategory = (v: unknown): v is RecipeCategory =>
  typeof v === 'string' && RECIPE_CATEGORY_SET.has(v);
