-- Expand RecipeCategory enum
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'BRUNCH';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'SMOOTHIE';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'STEW';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'PASTA';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'PIZZA';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'SANDWICH';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'BREAD';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'BAKING';
ALTER TYPE "RecipeCategory" ADD VALUE IF NOT EXISTS 'SAUCE';

-- Expand CuisineKey enum
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'GERMAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'BRITISH';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'VIETNAMESE';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'LEBANESE';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'MOROCCAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'BRAZILIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'RUSSIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'PERSIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'CARIBBEAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'FILIPINO';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'INDONESIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'PAKISTANI';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'CAUCASIAN';
ALTER TYPE "CuisineKey" ADD VALUE IF NOT EXISTS 'AFRICAN';
